// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6hAwddoPz_3ogt6ERnrtoFdwb8Ct-Hz8',
    appId: '1:973424098168:web:a9bef83797d3c6a371268d',
    messagingSenderId: '973424098168',
    projectId: 'taskapp-d2478',
    authDomain: 'taskapp-d2478.firebaseapp.com',
    storageBucket: 'taskapp-d2478.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC-Qjvh36iUlb5LybJwhw2DlQgAqNYofk',
    appId: '1:973424098168:android:15549bb43ac2402d71268d',
    messagingSenderId: '973424098168',
    projectId: 'taskapp-d2478',
    storageBucket: 'taskapp-d2478.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllZa7zivlcYLkdhUBbg2OBPwyeyoS3dQ',
    appId: '1:973424098168:ios:d58cd560fc84cfa871268d',
    messagingSenderId: '973424098168',
    projectId: 'taskapp-d2478',
    storageBucket: 'taskapp-d2478.firebasestorage.app',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBllZa7zivlcYLkdhUBbg2OBPwyeyoS3dQ',
    appId: '1:973424098168:ios:d58cd560fc84cfa871268d',
    messagingSenderId: '973424098168',
    projectId: 'taskapp-d2478',
    storageBucket: 'taskapp-d2478.firebasestorage.app',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6hAwddoPz_3ogt6ERnrtoFdwb8Ct-Hz8',
    appId: '1:973424098168:web:3581d6ff8dda429271268d',
    messagingSenderId: '973424098168',
    projectId: 'taskapp-d2478',
    authDomain: 'taskapp-d2478.firebaseapp.com',
    storageBucket: 'taskapp-d2478.firebasestorage.app',
  );
}
